### ISSUE TITLE
Proposal for add 'name' Parameter in WordPress Package and Cloud service install

### ISSUE THREAD

**Issue by mehrshaddarzi** [wp-packagist/wp-packagist#17]
In the next version of WordPress Package Management, we want to add the `name` parameter in the wordpress.json file.
this Parameter usage for a cloud package management service and Users can install Your custom package very easily.

What is the Proposal:

1) We Need a Web Hosting For creating a Micro Service API For Auth Users. Every user has a username that can use in your Package. for example, one user registered with username=daniel.

2) The daniel user can add name parameter in your WordPress Package management:

```yml
{
    "name": "daniel@news",
    "description": "My WordPress Package Manangment for creating News WordPress Site",
    "keywords": ["news", "wordpress", "sport"],
    "core": {
        "version": "latest",
        "locale": "en_US",
        "network": false
    },
    "config": {
      ...
```

3) daniel user can Push this Package with `wp pack push` command.
4) All Users can Install this Package with `wp pack install daniel@news` very easily.
- All security parameter e.g. `DB_PASSWORD` or `admin_password` sync with user global parameter, or If no existing ask from the user when installing the new package. 
- Packages are divided into two public and private categories. Private packages can only be used by the person who created them.
